/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.InscripcionData;
import AccesoADatos.MateriaData;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class AsignarNota extends javax.swing.JInternalFrame {
private AlumnoData alumData=new AlumnoData();
private MateriaData matData= new MateriaData();
private InscripcionData inscData= new InscripcionData(matData, alumData);
    /**
     * Creates new form AsignarNota
     */
    public AsignarNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtIdMateria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtIdAlumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtNota = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbAsignar = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtIdMateria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtIdMateria.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtIdMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(jtIdMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 76, 25));

        jLabel1.setBackground(new java.awt.Color(170, 194, 205));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ID ALUMNO:");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 25));

        jtIdAlumno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtIdAlumno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtIdAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(jtIdAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 76, 25));

        jLabel2.setBackground(new java.awt.Color(170, 194, 205));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("CALIFICACIÓN:");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 25));

        jLabel3.setBackground(new java.awt.Color(170, 194, 205));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID MATERIA:");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 110, 25));

        jtNota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtNota.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNotaActionPerformed(evt);
            }
        });
        jPanel1.add(jtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 76, 25));

        jLabel4.setBackground(new java.awt.Color(2, 64, 126));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Calificaciones");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 470, 36));

        jbAsignar.setBackground(new java.awt.Color(2, 64, 126));
        jbAsignar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbAsignar.setForeground(new java.awt.Color(255, 255, 255));
        jbAsignar.setText("Asignar Nota");
        jbAsignar.setAutoscrolls(true);
        jbAsignar.setContentAreaFilled(false);
        jbAsignar.setOpaque(true);
        jbAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAsignarActionPerformed(evt);
            }
        });
        jPanel1.add(jbAsignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -29, 470, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtIdMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdMateriaActionPerformed

    private void jtIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtIdAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtIdAlumnoActionPerformed

    private void jtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNotaActionPerformed

    private void jbAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAsignarActionPerformed
        try {
           inscData.actualizarNota(Integer.parseInt(jtIdAlumno.getText()), Integer.parseInt(jtIdMateria.getText()), Integer.parseInt(jtNota.getText()));          
        } catch(NumberFormatException e){
           JOptionPane.showMessageDialog(this, "Solo puede coloccar numeros. Vuelva a intentar");
        }finally{
        limpiar();
        }
            
      
        
    }//GEN-LAST:event_jbAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAsignar;
    private javax.swing.JTextField jtIdAlumno;
    private javax.swing.JTextField jtIdMateria;
    private javax.swing.JTextField jtNota;
    // End of variables declaration//GEN-END:variables
private void limpiar(){
jtIdAlumno.setText("");
jtIdMateria.setText("");
jtNota.setText("");
}
}
