/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Rodri
 */
public class LoginView extends javax.swing.JFrame {

    private ImageIcon imgOjoOn = new ImageIcon(getClass().getResource("/imagenes/ojoOn.png"));
    private ImageIcon imgOjoOff = new ImageIcon(getClass().getResource("/imagenes/ojoOff.png"));

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        textFieldUsuario.setBackground(new Color(0, 0, 0, 0));
        passwordField.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLinea = new javax.swing.JLabel();
        labelLinea1 = new javax.swing.JLabel();
        labelIcoClave = new javax.swing.JLabel();
        labelIcoUsuario = new javax.swing.JLabel();
        botonOjo = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        textFieldUsuario = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLinea.setBackground(new java.awt.Color(0, 0, 0));
        labelLinea.setOpaque(true);
        getContentPane().add(labelLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 220, 2));

        labelLinea1.setBackground(new java.awt.Color(0, 0, 0));
        labelLinea1.setOpaque(true);
        getContentPane().add(labelLinea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, 2));

        labelIcoClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llave30px.png"))); // NOI18N
        getContentPane().add(labelIcoClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 30, 30));

        labelIcoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario30px.png"))); // NOI18N
        getContentPane().add(labelIcoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 125, 30, 30));

        botonOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ojoOff.png"))); // NOI18N
        botonOjo.setBorderPainted(false);
        botonOjo.setContentAreaFilled(false);
        botonOjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOjoActionPerformed(evt);
            }
        });
        getContentPane().add(botonOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 185, 32, 32));

        passwordField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(153, 153, 153));
        passwordField.setText("CONTRASEÑA");
        passwordField.setBorder(null);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, 40));

        textFieldUsuario.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        textFieldUsuario.setForeground(new java.awt.Color(153, 153, 153));
        textFieldUsuario.setText("USUARIO");
        textFieldUsuario.setBorder(null);
        textFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldUsuarioFocusLost(evt);
            }
        });
        getContentPane().add(textFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 180, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 310, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOjoActionPerformed
        if (botonOjo.getIcon().equals(imgOjoOn)) {
            botonOjo.setIcon(imgOjoOff);
            passwordField.setEchoChar('*');

        } else {
            botonOjo.setIcon(imgOjoOn);
            passwordField.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_botonOjoActionPerformed

    private void textFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsuarioFocusGained
        if (!textFieldUsuario.getText().equals("")) {
            textFieldUsuario.setText("");
            textFieldUsuario.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textFieldUsuarioFocusGained

    private void textFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsuarioFocusLost
        if (textFieldUsuario.getText().equals("")) {
            textFieldUsuario.setText("USUARIO");
            textFieldUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textFieldUsuarioFocusLost

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        if (!passwordField.getText().equals("")) {
            passwordField.setText("");
            passwordField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        if (passwordField.getText().equals("")) {
            passwordField.setText("CONTRASEÑA");
            passwordField.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOjo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelIcoClave;
    private javax.swing.JLabel labelIcoUsuario;
    private javax.swing.JLabel labelLinea;
    private javax.swing.JLabel labelLinea1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
