/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Rodri
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        fondoEscritorio = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        menuItemCrearAlumno = new javax.swing.JMenuItem();
        menuItemModifAlumno = new javax.swing.JMenuItem();
        menuItemBorrarAlumno = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        menuAdministracion = new javax.swing.JMenu();
        menuConsultas = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondoEscritorio.setBackground(new java.awt.Color(204, 204, 204));
        fondoEscritorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondoEscritorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ulpLogoFondo.png"))); // NOI18N
        fondoEscritorio.setOpaque(true);

        escritorio.setLayer(fondoEscritorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumno");

        menuItemCrearAlumno.setText("Crear alumno");
        menuItemCrearAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearAlumnoActionPerformed(evt);
            }
        });
        menuAlumno.add(menuItemCrearAlumno);

        menuItemModifAlumno.setText("Modificar Alumno");
        menuAlumno.add(menuItemModifAlumno);

        menuItemBorrarAlumno.setText("Dar de baja");
        menuAlumno.add(menuItemBorrarAlumno);

        barraMenu.add(menuAlumno);

        menuMateria.setText("Materia");
        barraMenu.add(menuMateria);

        menuAdministracion.setText("Administración");
        barraMenu.add(menuAdministracion);

        menuConsultas.setText("Consultas");
        barraMenu.add(menuConsultas);

        menuSalir.setText("Salir");
        barraMenu.add(menuSalir);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCrearAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCrearAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel fondoEscritorio;
    private javax.swing.JMenu menuAdministracion;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuItemBorrarAlumno;
    private javax.swing.JMenuItem menuItemCrearAlumno;
    private javax.swing.JMenuItem menuItemModifAlumno;
    private javax.swing.JMenu menuMateria;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
